branch-defaults:
  dev:
    environment: FabFresh-dev
  master:
    environment: FabFresh
global:
  application_name: My First Elastic Beanstalk Application
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.03 v1.4.6 running Python 2.7
  default_region: eu-west-1
  profile: eb-cli
  sc: git
