branch-defaults:
  dev:
    environment: FabFresh
  master:
    environment: FabFresh-dev
global:
  application_name: My First Elastic Beanstalk Application
  default_ec2_keyname: rabbitmq-fabfresh
  default_platform: Python 2.7
  default_region: eu-west-1
  profile: eb-cli
  sc: git
